### ISSUE TITLE
Add option for concentration icon to mirror item/spell image

### ISSUE THREAD

**Issue by kerbsy** [krbz999/concentrationnotifier#2]
I would greatly appreciate an option for the concentration image to be derived from `item.data.img` on the item itself, instead of using the default or a custom image. I think it'd really help to get a quick sense of who's concentrating on what in the midst of battle, without having to check every single actor (the module's Dfred's Effect Panel integration does help a *ton* with this though)

Thankfully, you do already grab the name and duration, which *is* the more important info, but I believe this would be a nice addition as well. Enabling this setting should supersede the default and/or custom icon, unless perhaps the image cannot be found, though that may be a separate issue in of itself.

**Comment by krbz999** [comment]
Good idea. Added in 1.0.9.
