### ISSUE TITLE
Add option for confirmation dialog when you try to start concentrating on something else

### ISSUE THREAD

**Issue by benbarbour** [krbz999/concentrationnotifier#21]
My players would like it if, when they tried to use a concentration spell while already concentrating on something, they got a notification saying something like "are you sure you want to start concentrating on X? You will stop concentrating on Y!"

**Comment by krbz999** [comment]
A red/yellow/blue ui notification like those usually generated or something else?

**Comment by benbarbour** [comment]
I mean a dialog with an okay/cancel button so that concentration on the
first spell isn't interrupted.

**Comment by krbz999** [comment]
I like this idea, but I think what I will implement is a blue info notification in the AbilityUseDialog when you use an item or spell while already concentrating on something different. (And adding a setting to toggle this off.)
It seems fairly trivial to force the dialog to appear even for items that do not normally have it, if needed.

**Comment by benbarbour** [comment]
Sounds good!
