### ISSUE TITLE
[Request] Less messages in chat

### ISSUE THREAD

**Issue by maxobremer** [krbz999/concentrationnotifier#30]
It would be nice if there was an option to have less messages in chat. The message that someone starts or stop concentrating aren't really necessary for my games at least. Would be nice if those could be turned off, as the concentration effect already shows if they are or aren't concentrating on something.

Also a thank you for your hard work so far for the community Zhell. Good Job 👍

**Comment by krbz999** [comment]
Added in 10.1.2.
