### ISSUE TITLE
contains "system" which is deprecated in favor of "relationships.systems"

### ISSUE THREAD

**Issue by EasysGit** [krbz999/concentrationnotifier#33]
setup.js:145 [concentrationnotifier] module "concentrationnotifier" contains "system" which is deprecated in favor of "relationships.systems"
#logPackageWarnings @ setup.js:145
setup.js:145 [concentrationnotifier] The module "concentrationnotifier" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object

**Comment by krbz999** [comment]
The current module version is 10.1.5. Which are you on?

**Comment by EasysGit** [comment]
Sorry I was stuck on a ver9 build that refused to update. Uninstalling and reinstalling fixed the issue
