### ISSUE TITLE
Cant acces my foundry world settings while this module is active

### ISSUE THREAD

**Issue by maxobremer** [krbz999/concentrationnotifier#39]
Cant acces my foundry world settings while this module is active
![image](https://github.com/krbz999/concentrationnotifier/assets/86924581/e37ef23c-d76b-4c6f-a202-7d15891e8eab)
can acces it when i make this module inactive

Foundry v10 build 291
dnd5e 2.2.1
Concentration Notifier 10.2.0

**Comment by krbz999** [comment]
The change to `CONFIG.DND5E.abilities` in dnd5e v2.2.0 causes templates to fail rendering if modules did not accommodate. The previous release was written under the assumption that 2.2.0 would be v11-only. Backporting some changes and making the module compatible with v10 again to resolve this.
