### ISSUE TITLE
Concentration effect name is empty and acvtice effects delete concentration effects

### ISSUE THREAD

**Issue by maxobremer** [krbz999/concentrationnotifier#41]
When I cast for example bless, the concentration effect has no name
![image](https://github.com/krbz999/concentrationnotifier/assets/86924581/3c152387-48b3-4d4b-9f59-70667466d562)

If I cast bless and apply the active effect from the chat card, it deletes the concentration effect,
![image](https://github.com/krbz999/concentrationnotifier/assets/86924581/c6a8d535-f481-4dbc-9bbf-76f4f1bf0253)

Foundry v10 build 291
dnd5e 2.2.1

Modules of notes might be:
Dfred convenient effect (the effect on the bless spell came from dfred convenient effect and has such a flag so i can remove the effect with their build in remove effect button, without opening the sheet)
ready set roll (provides the chat card that applies the active effect from something like bless when i click the button in the chat card)

**Comment by krbz999** [comment]
Welp. Missed a spot.

**Comment by krbz999** [comment]
The second part of the issue looks to be ET. Possibly a clash given that it transfers by name (or label) unless the transfers are 'permanent'.

**Comment by maxobremer** [comment]
> The second part of the issue looks to be ET. Possibly a clash given that it transfers by name (or label) unless the transfers are 'permanent'.

but one has no name and the other does?

**Comment by krbz999** [comment]
It was a guess. If the concentration effects get randomly deleted while you have all other modules disabled, please open a separate issue and I will take a look (provide steps to reproduce it).

**Comment by maxobremer** [comment]
so tested it today with just midi and its dependencies
![image](https://github.com/krbz999/concentrationnotifier/assets/86924581/198d4e96-7a26-4994-9868-285402afc0d4)

the issue still happened

Foundry v11 build 302
DnD5e 2.2.1

![image](https://github.com/krbz999/concentrationnotifier/assets/86924581/47d21d62-521d-4e1e-9fa4-73ca546561f2)
with those modules active, roll the guidance spell and concentration on it start

![image](https://github.com/krbz999/concentrationnotifier/assets/86924581/1e6dfd10-17a4-43f4-b3d6-2650462e03d7)
target the token and click the in chat button to apply the effect, which does apply the effect but removes the concentration effect, despite both having a different name

**Comment by krbz999** [comment]
I would like to emphasize the "all other modules disabled" part. CN does not work with midi, and it should never be used with midi. It has always been, and will always be, incompatible with midi.

This is not an issue with CN.

**Comment by maxobremer** [comment]
Then what is it an issue with? like you need something to get a active affect in chat like that with a button to apply. Normally I use ready set roll, now I used the alternative, midi, and its still not good. Or is there some option in foundry i am not aware of that gives me a "apply active affect" button?
![image](https://github.com/krbz999/concentrationnotifier/assets/86924581/74318d53-2c0c-46e5-9d3e-d59658646a0a)

**Comment by krbz999** [comment]
If it is not an issue with CN, then discussion of it does not belong here.

**Comment by maxobremer** [comment]
I am no expert on the tech side of things, so maybe I am wrong, but if its a problem with 1 other module, might be an issue with the other modules, but if the issue is still there when an alternative other module is used, would it be that weird to assume maybe the issue relies with CN, not with two different modules.

or do those other modules use the exact same code to get that apply active effect button, so they simply make the same mistake twice? feels to me like thats less likely and its just an issue with CN. though again, no expert on code and tech and i could be wrong, just from my current perspective it seems like a CN issue.
