### ISSUE TITLE
Build JS files into a bundle to reduce requests

### ISSUE THREAD

**Issue by Fallayn** [krbz999/concentrationnotifier#47]
Hey! While debugging the large number of requests causing infrastructure issues when loading into Foundry, I saw that concentrationnotifier currently needs 15 requests for me on each load into Foundry:

```
15 concentrationnotifier
# 1 -> https://assets.forge-vtt.com/bazaar/modules/concentrationnotifier/11.0.8/styles/styles.css
# 2 -> https://assets.forge-vtt.com/bazaar/modules/concentrationnotifier/11.0.8/setup.mjs
# 3 -> https://assets.forge-vtt.com/bazaar/modules/concentrationnotifier/11.0.8/scripts/settings.mjs
# 4 -> https://assets.forge-vtt.com/bazaar/modules/concentrationnotifier/11.0.8/scripts/_characterFlags.mjs
# 5 -> https://assets.forge-vtt.com/bazaar/modules/concentrationnotifier/11.0.8/scripts/_createSheetCheckbox.mjs
# 6 -> https://assets.forge-vtt.com/bazaar/modules/concentrationnotifier/11.0.8/scripts/_gainLoseConcentrationTracker.mjs
# 7 -> https://assets.forge-vtt.com/bazaar/modules/concentrationnotifier/11.0.8/scripts/_promptCreator.mjs
# 8 -> https://assets.forge-vtt.com/bazaar/modules/concentrationnotifier/11.0.8/scripts/_promptListeners.mjs
# 9 -> https://assets.forge-vtt.com/bazaar/modules/concentrationnotifier/11.0.8/scripts/_publicAPI.mjs
# 10 -> https://assets.forge-vtt.com/bazaar/modules/concentrationnotifier/11.0.8/scripts/_renderAbilityUseDialog.mjs
# 11 -> https://assets.forge-vtt.com/bazaar/modules/concentrationnotifier/11.0.8/scripts/_rollConcentrationSave.mjs
# 12 -> https://assets.forge-vtt.com/bazaar/modules/concentrationnotifier/11.0.8/scripts/_startConcentration.mjs
# 13 -> https://assets.forge-vtt.com/bazaar/modules/concentrationnotifier/11.0.8/scripts/_helpers.mjs
# 14 -> https://assets.forge-vtt.com/bazaar/modules/concentrationnotifier/11.0.8/lang/de.json
# 15 -> https://assets.forge-vtt.com/bazaar/modules/concentrationnotifier/11.0.8/lang/en.json
```

Would be nice if you could bundle the JS files with a build step when distributing, so they are not all separate HTTP requests. If everyone does this, even 10 modules require 150 HTTP requests, and some people tend to have *way* more modules.

Thanks for the amazing module. <3

**Comment by krbz999** [comment]
After some further consideration, I can appreciate you looking into what is causing you issues in your setup, but I strongly doubt CN is to blame for that and such a change would not be worth the effort and maintenance neither here nor on babonus. So I am closing them as wontfix since, at best, the improvement would not even be noticeable.

**Comment by Fallayn** [comment]
I was never meaning to imply CN is to blame for anything.

CN's 15 requests do not break my setup, same for the 16 from Condition Lab or the 17 from Rideable or the 18 from Drag Ruler or the 30 from babonus or the 34 from limits :)

On its own, none of that matters, but the fact is that it is not super uncommon to have more than 5 modules, in which case these do add up. Even with just those 5 examples, each of them getting rid of 10 of those requests means 50 less HTTP requests on each load. Especially for users on poorer connections that matters.

And if you have 20 modules instead of 5, soon thats 200 requests.

Anyway, not looking to argue, just wanted to bring it up. Your module, your decision and all that, although I'm a bit sad of losing a few modules I liked :) Thanks for creating modules for the community, and thanks for responding!

**Comment by krbz999** [comment]
Put things into compendiums.

**Comment by Fallayn** [comment]
This was in an empty world without any compendiums. Foundry was breaking when initialising and loading modules, due to some CDN host/ISP in the middle resetting TCP connections when witnessing the request storm that Foundry with a few modules produces.
