### ISSUE TITLE
Ability "" does not exist after updating to newest version

### ISSUE THREAD

**Issue by nschoenwald** [krbz999/concentrationnotifier#51]
After updating to 11.1.0, I get this error when rolling constitution saves via the generated chat card:
<img width="1051" alt="image" src="https://github.com/krbz999/concentrationnotifier/assets/72390280/8da50185-eed6-48b4-a765-1b36618005f2">
My default concentration ability is set to constitution.
<img width="545" alt="image" src="https://github.com/krbz999/concentrationnotifier/assets/72390280/19ee4b47-804b-4498-8b77-1d2256884216">

I'm using current versions of foundry v11 and dnd5e and chrome browser.

**Comment by krbz999** [comment]
You're right that there is an issue, that is not a standard error message though. Somehow some module producing its own warnings.
