### ISSUE TITLE
Support multiple concentration effects

### ISSUE THREAD

**Issue by rapus95** [krbz999/concentrationnotifier#52]
Could be implemented either by replacing the "conc" togglebox of 5e with a dropdown, or by asking which group to populate a conc spell to on casting.

For reference, Witches have 2 concentration slots. One which can be populated with so-called hexes and one for ordinary concentration spells.

**Comment by krbz999** [comment]
Which witch would that be?

**Comment by rapus95** [comment]
https://www.reddit.com/r/dndnext/comments/s2g2c6/an_extensive_look_at_valdas_spire_of_secrets/

The homebrew one from Valdas Spire of Secrets.

**Comment by krbz999** [comment]
So is it within scope? Yes, it is, but I will accept a PR for this, and after only extensive review, given that it would require rewriting the module in its near entirety.
