### ISSUE TITLE
Can this work with latest DnD5e 3.1.1?

### ISSUE THREAD

**Issue by mrmattwilkins** [krbz999/concentrationnotifier#67]
It would be great if this could be updated to work with the latest, as of 2023-03-30, DnD5e (3.1.1).  Would this be possible?
Thanks
Matt

**Comment by krbz999** [comment]
I have no plans of updating 'Concentration Notifier' to work with dnd5e v3.1.x, as I put a lot of effort into building concentration tracking into the system itself; this module is no longer needed.

If there are features in this module that you think are missing in the system, you should make an issue there. :)

**Comment by mrmattwilkins** [comment]
Thanks Zhell.  Bit of a newby here, I didn't realize you had got the functionality into dnd5e v3.1.x.  I appreciate that, thank you!
Matt
